[theme]
primaryColor = "#173F57"
backgroundColor = "#F4F6F8"
secondaryBackgroundColor = "#EEF2F4"
textColor = "#162736"
font = "sans serif"

[server]
maxUploadSize = 20
headless = true

[client]
showErrorDetails = false
toolbarMode = "minimal"
