[theme]
primaryColor = "#075FCB"
backgroundColor = "#F2F6FB"
secondaryBackgroundColor = "#E9F0FA"
textColor = "#0A1E3B"
font = "sans serif"

[server]
maxUploadSize = 20
headless = true

[client]
showErrorDetails = false
toolbarMode = "minimal"
